// Textos de arranque de las cotizaciones DISERCO (se pueden editar en cada cotización). Igual que la app original.
export const SECCIONES_PROYECTO = [
  { titulo: 'Comentarios adicionales', texto: 'Tiempo de ejecución estimado: 4 a 5 días, asumiendo que el área está lista para intervenir (libre de equipos y personal). La duración puede acortarse mediante jornadas nocturnas, si el cliente lo solicita y la zona se entrega libre.\nTiempos de curado y habilitación:\n- Tráfico liviano y mediano: 12 horas.\n- Tráfico pesado: 36 horas.\nGarantía: 2 años.\nVida útil estimada: entre 5 y 7 años, dependiendo del uso.' },
  { titulo: 'Estructura del sistema (espesores aproximados)', texto: '- Preparación industrial del piso.\n- Resane de juntas y defectos.\n- Primer: 0.12–0.25 mm.\n- Cuerpo de resina (3 manos): 1 mm.\n- Top de poliuretano: 0.10 - 0.15 mm.' },
  { titulo: 'Equipo de seguridad y herramientas', texto: 'Se incluyen en la oferta las herramientas y equipos necesarios para la correcta instalación del sistema, tales como equipos de preparación mecánica de superficie, mezcladores industriales para resina, rodillos, llana, espátulas, calibradores de espesor, equipos de medición y herramientas manuales especializadas. Asimismo, el personal contará con todo el EPP requerido conforme a las normas de seguridad industrial.' },
  { titulo: 'Ventajas de trabajar con nosotros', texto: '1) Experiencia de mas de 18 años en recubrimientos industriales y pulidos de concreto\n2) Personal capacitado por expertos\n3) Supervisión de alto nivel\n4) Equipo de ultima generación para preparación de superficie y pulidos de pisos\n5) Garantía en la instalación\n6) Rapidez en el tiempo de ejecución\n7) Garantía en materiales y mano de obra' },
  { titulo: 'Observaciones', texto: 'a) Solicitamos se nos provea de una bodega segura para almacenar equipo y materiales en el sitio de trabajo.\nb) Se incluyen trabajos horarios nocturnos y de doble turno a nuestra conveniencia.\nc) Se deberá proporcionar energía eléctrica 110V y 220V, y agua potable.\nd) Esta oferta no contempla reparación de huecos, grietas u otros problemas que puedan encontrarse en el concreto existente.\ne) El área a trabajar deberá estar limpia y libre de tránsito, tanto de equipo como de personal durante todo el proceso de aplicación.' },
  { titulo: 'Forma de pago', texto: 'Se solicita el 50% de anticipo y el 50% restante al finalizar la obra.' },
  { titulo: '*No incluye esta oferta', texto: 'Obras civiles de ningún tipo.\nNi ningún otro no especificado en esta oferta.' },
];
export const SECCIONES_PRODUCTOS = [{ titulo: 'Rendimientos aproximados', texto: '' }];
export const FIRMA_DEFECTO = { firma_nombre: 'Damaris Trochez', firma_cargo: 'Asistente Administrativo' };
